version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: dend
    ports:
      - 27018:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

volumes:
  data: {}

networks:
  default:
    name: mongodb_network
